# Cloudflare Workers configuration
name = "sellmyseats-rgnack"
compatibility_date = "2023-09-01"
main = "dist/index.js"
workers_dev = true

# Define production domain
routes = [
  { pattern = "sellmyseats.rgnack.com", custom_domain = true }
]

# Define environment variables
[vars]
DEPLOYMENT_ENV = "production"

# Setup Cloudflare Pages asset hosting
[site]
bucket = "./dist"

# Define environment specific configuration
[env.production]
routes = [
  { pattern = "sellmyseats.rgnack.com", custom_domain = true }
]

[env.production.vars]
NODE_ENV = "production"

# D1 Database (if you're using Cloudflare D1)
# [[d1_databases]]
# binding = "DB"
# database_name = "sellmyseats"
# database_id = "" # You'll need to create this and get the ID

# KV Namespace (for caching if needed)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "" # You'll need to create this and get the ID 